import React from 'react';
import  ModalContainer from '../../global/components/ModalContainer';
import ScrollBar  from '../../global/components/ScrollBar';

import "../styles/TermsAndConditions.scss";

const TermsAndConditions = props => (
    <div className="tnc_modal">
    <ModalContainer 
        title="Terms and Conditions - License Agreement"
        content={
            <ScrollBar>
            <div id="tnc_content">
                <h4 className="tnc_header">SOFTWARE TRIAL LICENSE AGREEMENT</h4>
                <p className="tnc_bold">THIS SOFTWARE TRIAL LICENSE AGREEMENT (“LICENSE AGREEMENT”) IS A LEGAL CONTRACT BETWEEN AVO AUTOMATION PTE. LTD (“LICENSOR”) AND YOU, EITHER AS AN INDIVIDUAL OR AN ENTITY (“LICENSEE”). IF THE LICENSEE IS ACCEPTING ON BEHALF OF AN ENTITY, THE LICENSEE REPRESENTS AND WARRANTS THAT THE LICENSEE HAS THE AUTHORITY TO BIND THAT ENTITY TO THIS AGREEMENT  LICENSORIS WILLING TO AUTHORIZE LICENSEE’S USE OF THE SOFTWARE ASSOCIATED WITH THIS LICENSE AGREEMENT ONLY UPON THE CONDITION THAT LICENSEE ACCEPTS THIS LICENSE AGREEMENT WHICH GOVERNS LICENSEE’S USE OF THE SOFTWARE. BY DOWNLOADING, INSTALLING, OR ACCESSING AND USING THE SOFTWARE, LICENSEE INDICATES LICENSEE’S ACCEPTANCE OF THIS LICENSE AGREEMENT AND LICENSEE’S AGREEMENT TO COMPLY WITH THE TERMS AND CONDITIONS OF THIS LICENSE AGREEMENT.</p>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">1.        </span> DEFINITIONS</h5>
                    <div>
                        <p><span className="tnc_num_idx">1.1.    </span> <b>Specific Words or Phrases.</b> For purposes of this License Agreement, each word or phrase listed below shall have the meaning designated. Other words or phrases used in this License Agreement may be defined in the context in which they are used and shall have the respective meaning there designated.</p>
                        <p>"<b>Affiliate</b>" means and includes any entity that directly or indirectly controls, is controlled by, or is under common control with Licensee, where "control" means the ownership of, or the power to vote, at least fifty percent (50%) of the voting stock, shares or interests of such entity. An entity that otherwise qualifies under this definition will be included within the meaning of "Affiliate" even though it qualifies after the execution of this Agreement.</p>
                        <p>"<b>License Agreement</b>" or "<b>Agreement</b>" means the terms of this Software Trial License Agreement, together with the appendices and other exhibits attached hereto or incorporated herein by reference.</p>
                        <p>"<b>Authorized Users</b>" shall mean and include Licensee, its employees and contract employees of the Licensee who are working for the Licensee.</p>
                        <p>"<b>Intellectual Property Rights</b>" means all trade secrets, patents and patent applications, trademarks (whether registered or unregistered and including any goodwill acquired in such trade marks), service marks, trade names, business names, internet domain names, e-mail address names, copyrights (including rights in computer software), moral rights, database rights, design rights, rights in know-how, rights in confidential information, rights in inventions (whether patentable or not) and all other intellectual property and proprietary rights (whether registered or unregistered, and any application for the foregoing), and all other equivalent or similar rights which may subsist anywhere in the world.</p>
                        <p>"<b>License</b>" means a license to use the Software granted pursuant to the terms and conditions of this License Agreement.</p>
                        <p>"<b>Licensee</b>" means the person or entity that has entered into this License Agreement.</p>
                        <p>"<b>Licensor</b>" means Avo Automation Pte Ltd.</p>
                        <p>"<b>Party</b>" means either the "Licensor" or "Licensee", individually as the context so requires; and "<b>Parties</b>" means the "Licensor" and "Licensee", collectively.</p>
                        <p>"<b>Personnel</b>" means and includes a Party’s or an Affiliate’s directors, officers, employees, agents, auditors, consultants, contract employees and subcontractors.</p>
                        <p>"<b>Software</b>" means the appropriate software product licenses made available to Licensee and its Authorized Users by Licensor under this License Agreement.</p>
                    </div>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">2.        </span> TERM AND TERMINATION</h5>
                    <p><span className="tnc_num_idx">2.1.    </span> <b>Term.</b> This License Agreement shall remain in effect for a period of fifteen (15) days from the date of download of the Software (‘Term’). The License term shall automatically expire on the end of the Term.</p>
                    <p><span className="tnc_num_idx">2.2.    </span> <b>Termination for Cause.</b> If Licensee breaches a material obligation under this Agreement, then Licensor may terminate this Agreement with immediate effect.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">3.        </span> CONSEQUENCE OF TERMINATION</h5>
                    <p><span className="tnc_num_idx">3.1.    </span> <b> Return of Software.</b> Upon termination of this License Agreement, under any or all of the reasons mentioned in this License Agreement or on expiry of the License Agreement, the license granted to Licensee by Licensor herein shall terminate and Licensee shall cease to use the Software immediately and return or destroy, at Licensor’s option, the original and all copies of the Software and Documentation including partial copies immediately on the date of such termination/expiration. Licensee shall not from the date of termination or expiry of the License Agreement, be entitled to use or access the Software or Documentation in any manner whatsoever, and Licensor shall have a reasonable opportunity to conduct an inspection of Licensee's place of business to assure compliance with this provision.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">4.        </span> SCOPE OF LICENSE</h5>
                    <p><span className="tnc_num_idx">4.1.    </span> <b>Proprietary Rights to Software.</b> As between Licensor and Licensee, Licensor shall be deemed to own the Intellectual Property Rights in or to the Software; and nothing contained in this License Agreement shall be construed to convey any Intellectual Property Rights in or to the Software to Licensee (or to any party claiming through Licensee) other than the license rights expressly set forth in this License Agreement.</p>
                    <p><span className="tnc_num_idx">4.2.    </span> <b>License Grant.</b></p>
                    <p className="tnc_third"><span className="tnc_num_idx">4.2.1.  </span> As between Licensor and Licensee, Licensor shall be deemed to own the Intellectual Property Rights in or to the Software; and nothing contained in this License Agreement shall be construed to convey any Intellectual Property Rights in or to the Software to Licensee (or to any party claiming through Licensee) other than the license rights expressly set forth in this License Agreement.</p>
                    <p><span className="tnc_num_idx">4.3.    </span> <b>Restrictions.</b> Except to the extent authorized or permitted in this License Agreement or by applicable law without the possibility of contractual waiver, Licensee shall not directly or indirectly: (i) copy, modify, create derivative work; (ii), transfer or distribute the Software (electronically or otherwise); (iii) reverse assemble, reverse engineer, reverse compile, or otherwise translate the Software; (iv) sublicense or assign the license for the Software; (v) remove, delete or alter any content, trademark, copyright or other intellectual property rights from the Software including any copies thereof; (vi) use the Software in violation of the applicable laws.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">5.        </span> REPRESENTATIONS AND WARRANTIES</h5>
                    <p><span className="tnc_num_idx">5.1.    </span> <b>Authority and Non-Infringement.</b> Licensor represents and warrants that Licensor has all rights and authority required to enter into this License Agreement, and to provide the Software and perform the services contemplated by this License Agreement, free from all liens, claims, encumbrances, security interests and other restrictions. Subject to the applicable terms and conditions of this License Agreement, Licensee will be entitled to use and enjoy the benefit of all Software without adverse interruption or disturbance by Licensor or any entity asserting a claim under or through Licensor. Licensor further represents and warrants that the Software  and the use thereof by Licensee in accordance with the terms and conditions of this License Agreement, will not infringe (whether directly, contributorily, by inducement or otherwise), misappropriate or violate the Intellectual Property Rights of any third party, or violate the laws, regulations or orders of any governmental or judicial authority. Licensee represents and warrants that Licensee has all rights and authority required to enter into this License Agreement and Licensee has provided inaccurate information about itself for accessing the Software.</p>
                    <p><span className="tnc_num_idx">5.2.    </span> <b>Standard of Service.</b> Licensor warrants that the maintenance service provided by Licensor pursuant to this License Agreement or any other agreement relating to the Software, will be performed in a timely and professional manner, in conformity with standards generally accepted in the software industry, by qualified and skilled individuals. Licensor further warrants that its personnel will provide services with a minimal amount of interference to Licensee’s normal business operations and subject to Licensee’s security and work place policies and procedures.</p>
                    <p><span className="tnc_num_idx">5.3.    </span> <b>Disabling Devices.</b> Licensor represents and warrants that at the time of download the Software shall not contain any computer code or any other procedures, routines or mechanisms designed by Licensor (or its personnel or licensors) to: (i) disrupt, disable, harm or impair in any way the Software’s (or any other software’s) orderly operation based on the elapsing of a period of time advancement to a particular date or other numeral (sometimes referred to as “time bombs”, “time locks”, or “drop dead” devices); (ii) cause the Software to damage or corrupt any of Licensee’s, data, storage media, programs, equipment or communications, or otherwise interfere with Licensee’s use of the Software in accordance with this Agreement, or (iii) permit Licensor, its personnel, or any other third party, to access the Software (or any other software or Licensee’s or its Affiliates’ computer systems) for any reason (sometimes referred to as “traps”, “access codes” or “trap door” devices).</p>
                    <p><span className="tnc_num_idx">5.4.    </span> <b>Disclaimer. EXCEPT FOR THE REPRESENTATIONS AND WARRANTIES EXPRESSLY SET FORTH IN THIS LICENSE AGREEMENT OR THE AGREEMENT, THE SOFTWARE AND DOCUMENTATION ARE LICENSED “AS IS,” AND LICENSOR DISCLAIMS ANY AND ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO THE SOFTWARE, THE DOCUMENTATION, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE</b></p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">6.        </span> CONFIDENTIAL INFORMATION</h5>
                    <p><span className="tnc_num_idx">6.1.    </span> <b>Licensor’s Confidential Information.</b> Licensor’s “Confidential Information” means and refers to (i) the Software, (ii) the Documentation, (iii) information or materials related to Licensor’s trade secrets, business plans, strategies, forecasts or forecast assumptions, operations, methods of doing business, records, finances, assets, technology, (iv) information or materials that reveal research, technology, practices, procedures, processes, methodologies, know how, or other systems or controls by which Licensor’s products, services, applications and methods of operations or doing business are developed, conducted or operated, and (v) all other materials furnished by Licensor that are expressly identified or marked by Licensor as “confidential” at the time of their delivery to Licensee.</p>
                    <p><span className="tnc_num_idx">6.2.    </span> <b>Licensee’s “Confidential Information”.</b> Licensee’s “Confidential Information” means and refers to all information and materials, in any form or medium (and without regard to whether the information or materials are owned by Licensee or by a third party), furnished or disclosed to Licensor by Licensee , or otherwise obtained, accessed or observed by Licensor from Licensee).</p>
                    <p><span className="tnc_num_idx">6.3.    </span> <b>Duty of Care.</b> The Party receiving (“Receiving Party”) Confidential Information of the other Party (“Disclosing Party”) will exercise at least the same degree of care with respect to the Disclosing Party’s Confidential Information that the Receiving Party exercises to protect its own Confidential Information; and, at a minimum, the Receiving Party will maintain adequate security measures to safeguard the Disclosing Party’s Confidential Information from unauthorized disclosure, access, use and misappropriation. Without limiting the generality of the foregoing, the Receiving Party will only use or reproduce the Disclosing Party’s Confidential Information to the extent necessary to enable the Receiving Party to fulfill its obligations under this Agreement, or in the case of Licensee, to exercise its rights as contemplated by this Agreement. In addition, the Receiving Party will disclose the Disclosing Party’s Confidential Information only to those of the Receiving Party’s (or in the case of Licensee, also to its Affiliates’) Personnel who have a “need to know” such Confidential Information (and only to the extent necessary) in order to fulfill the purposes contemplated by the Agreement. Prior to disclosing Licensee’s Confidential Information to any of its Personnel, Licensor will ensure that each of its Personnel who will be providing services for Licensee is bound by a written non-disclosure agreement with terms and conditions no less restrictive than those set forth herein. If the Receiving Party becomes aware of any threatened or actual unauthorized access to, use or disclosure of, or any inability to account for, the Disclosing Party’s Confidential Information, the Receiving Party will promptly notify the Disclosing Party thereof and will assist the Disclosing Party with its efforts to terminate such access, to curtail such threatened or actual unauthorized use or disclosure, or to recover such information or materials. The Receiving Party will be liable to the Disclosing Party for any non-compliance by its agents or contractors to the same extent it would be liable for non-compliance by its employees.</p>
                    <p><span className="tnc_num_idx">6.4.    </span> <b>Exclusions.</b> The obligations of confidentiality assumed under this Agreement shall not apply to the extent the Receiving Party can demonstrate, by clear and convincing evidence, that such information:</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.4.1.  </span> is or has become generally available to the public, without any breach by the Receiving Party of the provisions of this Agreement or any other applicable agreement between the Parties;</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.4.2.  </span> was rightfully in the possession of the Receiving Party, without confidentiality restrictions, prior to such Party’s receipt pursuant to this Agreement;</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.4.3.  </span> was rightfully acquired by the Receiving Party from a third party who was entitled to disclose such information, without confidentiality or proprietary restrictions;</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.4.4.  </span> was independently developed by the Receiving Party without using or referring to the Disclosing Party’s Confidential Information; or,</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.4.5.  </span> is subject to a written agreement pursuant to which the Disclosing Party authorized the Receiving Party to disclose the subject information.</p>
                    <p><span className="tnc_num_idx">6.5.    </span> <b>Legally Required Disclosures.</b> The obligations of confidentiality assumed under this Agreement shall not apply to the extent that the Receiving Party is required to disclose the Disclosing Party’s Confidential Information under any applicable law, regulation or an order from a court, regulatory agency or other governmental authority having competent jurisdiction, provided that the Receiving Party:</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.5.1.  </span> promptly notifies the Disclosing Party of the order in order to provide the Disclosing Party an opportunity to seek a protective order;</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.5.2.  </span> provides the Disclosing Party with reasonable cooperation in its efforts to resist the disclosure, upon reasonable request by the Disclosing Party and at the Disclosing Party’s expense; and,</p>
                    <p className="tnc_third"><span className="tnc_num_idx">6.5.3.  </span> Disclose only the portion of the Disclosing Party’s Confidential Information that is required to be disclosed under such law, regulation or order.</p>
                    <p><span className="tnc_num_idx">6.6.    </span> <b>Accounting for Confidential Information.</b> Except as otherwise expressly provided in this Agreement, upon the request of the Disclosing Party at any time after the termination of this Agreement, the Receiving Party will return (or purge its systems and files of, and suitably account for) all Confidential Information supplied to, or otherwise obtained by, the Receiving Party in connection with this Agreement. The Receiving Party will certify in writing that it has fully complied with its obligations under this Section within seven (7) days after its receipt of a request by the Disclosing Party for such a certification. For the avoidance of doubt, this Section 6.6 shall not be construed to limit either Party’s right to seek relief from damages that are caused by the other Party’s default.</p>
                    <p><span className="tnc_num_idx">6.7.    </span> <b>DISCLAIMER ON DATA:- LICENSOR DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, LIABILITY RELATING TO SECURITY, CONFIDENTIALITY AND PROTECTION OF ALL DATA PROVIDED/TRANSFERRED/UPLOADED, IF ANY, BY LICENSEE IN THE ANY CLOUD ENVIRONMENT AS A PART OF LICENSING/USING THE SOFTWARE FROM ANY CLOUD ENVIRONMENT AND ANY SUCH TRANSFER/UPLOAD OF DATA SHALL BE AT LICENSEE’S OWN RISK.</b></p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">7.        </span> INDEMNITY</h5>
                    <p><span className="tnc_num_idx">7.1.    </span> Notwithstanding any limitations, exclusions, restrictions or exculpatory provisions as to liability or damages set forth in this License Agreement, Licensor agrees to indemnify, hold harmless and defend Licensee and its directors, officers, shareholders, employees, successors, assigns, agents, contractors, subcontractors, attorneys, and affiliates from and against any and all losses, costs, claims, liabilities, damages and expenses, including (without limitation) reasonable attorneys’ fees, arising as the result of (a) any breach of any of the representations, warranties, covenants, agreements or obligations of Licensor, (b) any negligence or willful misconduct on the part of Licensor, its employees, agents, subcontractors or subservicers, or (c) any judgment or finding, or any demand, assertion or claim, that any evaluation products or intellectual property provided to Licensee by Licensor in connection with the License Agreement infringes upon any patent, copyright, and/or trademark or any other enforceable proprietary or intellectual property rights of any third party or parties. The provisions of this section shall survive the expiration or termination of this Agreement.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">8.        </span> LIMITATION OF LIABILITY</h5>
                    <p>LICENSOR WILL NOT BE LIABLE TO THE OTHER PARTY (OR TO ANY PERSON OR ENTITY CLAIMING THROUGH THE OTHER PARTY) FOR LOST PROFITS OR FOR SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF OR IN ANY MANNER CONNECTED WITH THIS AGREEMENT OR THE SUBJECT MATTER HEREOF, REGARDLESS OF THE FORM OF ACTION AND WHETHER OR NOT SUCH PARTY HAS BEEN INFORMED OF, OR OTHERWISE MIGHT HAVE ANTICIPATED, THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING CONTAINED HEREIN, LICENSOR’S TOTAL LIABILITY, (WHETHER IN CONTRACT, TORT, INCLUDING NEGLIGENCE, OR OTHERWISE) UNDER OR IN CONNECTION WITH THIS AGREEMENT SHALL NOT EXCEED USD $1.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">9.        </span> SUBCONTRACTORS</h5>
                    <p>Licensor may subcontract its obligations under this Agreement without obtaining Licensee’s prior written approval.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">10.        </span> ASSIGNMENT</h5>
                    <p>Licensee may, with notice to Licensor, assign this Agreement or any of its rights or interests hereunder, or delegate any of its obligations hereunder, to (i) an Affiliate, (ii) Licensee's successor pursuant to a merger, reorganization, consolidation or sale, or (iii) an entity that acquires all or substantially all of that portion of Licensee’s assets or business for which the Licensor’s Software or services were acquired or being used.  Licensor may, with notice to Licensee, assign this Agreement (in whole and not in part), to (i) a wholly owned subsidiary, or (ii) Licensee's successor pursuant to a merger, reorganization, consolidation or sale. Except as otherwise provided above, neither Party may assign this Agreement nor any of its rights or interests hereunder, nor delegate any obligation to be performed hereunder, without the prior written consent of the other Party, which consent shall not be unreasonably withheld or delayed. Any attempted assignment or delegation in contravention of this Section shall be null and void, and of no force or effect. This Agreement shall be binding upon, and shall inure to the benefit of, the legal successors and permitted assigns of the Parties.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">11.        </span> NOTICES</h5>
                    <p>Any notice, demand or other communication (collectively “notice”) required or permitted under this Agreement shall be made in writing and shall be deemed to have been duly given (i) when delivered personally to the representative(s) designated to receive notices for the intended recipient, or (ii) when mailed by certified mail (return receipt requested) or sent by overnight courier to the representative(s) designated to receive notices for the intended recipient at the address set forth in the introductory paragraph of this Agreement, as appropriate. Notices concerning the Agreement shall be given to the person who signed the Agreement on behalf of the intended recipient. Any notice from Licensor that alleges Licensee committed a material breach shall also be sent to Licensee’s General Counsel’s Office, to the attention of the managing attorney responsible for intellectual property and technology. Either Party may change its address (es) or representative(s) for receiving notices upon notice to the other.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">12.        </span> COMPLIANCE WITH LAW</h5>
                    <p><span className="tnc_num_idx">12.1.    </span> <b>General.</b> In performing its obligations under this Agreement, both the parties will comply, and will cause its Personnel to comply, with the requirements of all applicable laws, ordinances, regulations, codes and executive orders.</p>
                    <p><span className="tnc_num_idx">12.2.    </span> <b>Export Controls.</b> Without limiting the generality of Section 12.1, Licensor specifically agrees to comply, and will cause its Personnel to comply, with the requirements of all applicable export laws and regulations, including but not limited to the U.S. Export Administration Regulations. Unless authorized by U.S. regulation or Export License, Licensor will not export or re-export, directly or indirectly, any software or technology received from Licensee, or allow the direct product thereof to be exported or re-exported, directly or indirectly, to (a) any country in Country Group E:2 of the Export Administration Regulations of the Department of Commerce or any other country subject to sanctions administered by the Office of Foreign Assets Control or (b) any non-civil (i.e. military) end-users or for any non-civil end-uses in any country in Country Group D:1 of the Export Administration Regulations, as revised from time to time. Licensor understands that countries other than the U.S. may restrict the import or use of strong encryption products and may restrict exports, and Licensor agrees that it shall be solely responsible for compliance with any such import or use restriction.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">13.        </span> CHOICE OF LAW, JURISDICTION</h5>
                    <p><b>Governing Law.</b> The Parties hereby agrees that this License Agreement shall be governed by and construed in accordance with the laws of Singapore.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">14.        </span> REMEDIES</h5>
                    <p><b>Equitable Relief.</b> Licensor and Licensee each acknowledge that the failure to perform their respective duties under <b>Sections 6, 7 or 8</b> may cause the other Party to suffer irreparable injury for which such injured Party will not have an adequate remedy available at law. Accordingly, the injured Party may seek to obtain injunctive or other equitable relief to prevent or curtail any such breach, threatened or actual, without posting a bond or security and without prejudice to such other rights as may be available under this Agreement or under applicable law. For purposes of this Agreement, "equitable relief" means and includes those remedies traditionally and historically granted by courts of equity, including without limitation, injunction, attachment, declaratory relief.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">15.        </span> WAIVER</h5>
                    <p>No course of dealing, failure by either Party to require the strict performance of any obligation assumed by the other hereunder, or failure by either Party to exercise any right or remedy to which it is entitled, shall constitute a waiver or cause a diminution of the obligations or rights provided under this Agreement. No provision of this Agreement shall be deemed to have been waived by any act or knowledge of either Party, but only by a written instrument signed by a duly authorized representative of the Party to be bound thereby. Waiver by either Party of any default shall not constitute a waiver of any other or subsequent default.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">16.        </span> FORCE MAJEURE</h5>
                    <p>A Party will be excused from a delay in performing, or a failure to perform, its obligations under this Agreement to the extent such delay or failure is caused by the occurrence of any contingency beyond the reasonable control, and without any fault, of such Party. In such event, the performance times shall be extended for a period of time equivalent to the time lost because of the excusable delay. However, if an excusable delay continues more than sixty (60) days, the Party not relying on the excusable delay may, at its option, terminate the Agreement in whole or in part, upon notice to the other Party. In order to avail itself of the relief provided in this Section for an excusable delay, the Party must act with due diligence to remedy the cause of, or to mitigate or overcome, such delay or failure.</p>
                </div>
                <div>
                    <br/>
                    <h5><span className="tnc_num_idx">17.        </span> CONSTRUCTION</h5>
                    <p><span className="tnc_num_idx">17.1.    </span> <b>Inconsistencies.</b> In the event of any inconsistency between the provisions of this Agreement and the Appendix-A, the provisions of the Appendix-A shall govern for purposes of such Appendix-A. The provisions of this Agreement and the Appendix-A shall supersede the provisions of any shrink-wrap, click wrap or other license provisions included with the Software.</p>
                    <p><span className="tnc_num_idx">17.2.    </span> <b>Modification.</b> The terms, conditions, covenants and other provisions of this Agreement may hereafter be modified, amended, supplemented or otherwise changed only by a written instrument (excluding e-mail or similar electronic transmissions) that specifically purports to do so and is physically executed by a duly authorized representative of each Party.</p>
                    <p><span className="tnc_num_idx">17.3.    </span> <b>Severability.</b> If a court of competent jurisdiction declares any provision of this Agreement to be invalid, unlawful or unenforceable as drafted, the Parties intend that such provision be amended and construed in a manner designed to effectuate the purposes of the provision to the fullest extent permitted by law. If such provision cannot be so amended and construed, it shall be severed, and the remaining provisions shall remain unimpaired and in full force and effect to the fullest extent permitted by law.</p>
                </div>
                <br/>
                <p><b>By clicking the “Agree” button, Licensee hereby agrees to be bound by all the terms and conditions stated herein</b></p>
            </div>
            </ScrollBar>
        }
        close={()=>props.tcAction('decline')}
        footer={
            <>
            <button onClick={()=>props.tcAction('Accept')}>Accept</button>
            <button onClick={()=>props.tcAction('Decline')}>Decline</button>
            </>
        }
    />
    </div>
)

export default TermsAndConditions;