export const SET_USERINFO = "LOGIN_SET_USERINFO"
export const SET_SR = "LOGIN_SET_SR"
export const SET_SOCKET = "LOGIN_SET_SOCKET"
export const UPDATE_NOTIFY = "LOGIN_UPDATE_NOTIFY"
export const CLEAR_NOTIFY = "LOGIN_CLEAR_NOTIFY"
export const UPDATE_NOTIFY_COUNT = "LOGIN_UPDATE_NOTIFY_COUNT"
export const SET_DATEFORMAT = "LOGIN_SET_DATEFORMAT"
export const HIGHLIGHT_AGS = "HIGHLIGHT_GENIUS";