export const UPDATE_PROJECTLIST = 'MINDMAP_UPDATE_PROJECTLIST';

export const SELECT_PROJECT = 'MINDMAP_SELECT_PROJECT';

export const UPDATE_MODULELIST = 'MINDMAP_UPDATE_MODULELIST';

export const SELECT_MODULE = 'MINDMAP_SELECT_MODULE';

export const SELECT_MODULELIST = 'MINDMAP_SELECT_MODULELIST';

export const SEARCH_MODULELIST = 'MINDMAP_SEARCH_MODULELIST';

export const SELECT_SELECTBOX = 'MINDMAP_SELECT_SELECTBOX';

export const UPDATE_SELECTNODES = 'MINDMAP_UPDATE_SELECTNODES';

export const UPDATE_COPYNODES = 'MINDMAP_UPDATE_COPYNODES';

export const UPDATE_SCREENDATA = 'MINDMAP_UPDATE_SCREENDATA';

export const UPDATE_DELETENODES = 'MINDMAP_UPDATE_DELETENODES';

export const UPDATE_SCENARIOLIST = 'MINDMAP_UPDATE_SCENARIOLIST';

export const SAVE_MINDMAP = 'MINDMAP_SAVE_MINDMAP';

export const UPDATE_UNASSIGNTASK = 'MINDMAP_UPDATE_UNASSIGNTASK';

export const INIT_ENEPROJECT = 'MINDMAP_INIT_ENEPROJECT';

export const IS_ENELOAD = 'MINDMAP_IS_ENELOAD';

export const IMPORT_MINDMAP = 'MINDMAP_IMPORT_MINDMAP';

export const DELETE_SCENARIO = 'MINDMAP_DELETE_SCENARIO';

export const DELETE_SCENARIOETE = 'MINDMAP_DELETE_SCENARIOETE';

export const APP_TYPE_FOR_PROJECT = 'APP_TYPE_FOR_PROJECT';
export const SAVED_LIST = 'SAVED_LIST';