export const UPDATE_PROJECTLIST = 'MINDMAP_UPDATE_PROJECTLIST';

export const SELECT_PROJECT = 'MINDMAP_SELECT_PROJECT';

export const UPDATE_MODULELIST = 'MINDMAP_UPDATE_MODULELIST';

export const SELECT_MODULE = 'MINDMAP_SELECT_MODULE';

export const SEARCH_MODULELIST = 'MINDMAP_SEARCH_MODULELIST';

export const SELECT_SELECTBOX = 'MINDMAP_SELECT_SELECTBOX';

export const UPDATE_SELECTNODES = 'MINDMAP_UPDATE_SELECTNODES'

export const UPDATE_COPYNODES = 'MINDMAP_UPDATE_COPYNODES';