export const UPDATE_MODULESELECTED = 'REPORT_UPDATE_MODULESELECTED';

export const UPDATE_MODULELIST = 'REPORT_UPDATE_PROJECTLIST';

export const UPDATE_SUITEDETAILS =  'REPORT_UPDATE_SUITEDETAILS';

export const RESET_DETAILS = 'REPORT_RESET_DETAILS'