export const SET_SCRAPEDATA = "SS_SET_SCRAPEDATA";
export const SET_DISABLEACTION = "SS_SET_DISABLEACTION";
export const SET_DISABLEAPPEND = "SS_SET_DISABLEAPPEND";
export const SET_COMPAREFLAG = "SS_SET_COMPAREFLAG";
export const SET_COMPAREDATA = "SS_SET_COMPAREDATA";
export const SET_COMPAREOBJ = "SS_SET_COMPAREOBJ";
export const SET_OBJVAL = "SS_SET_OBJVAL";
export const SET_CERT = "WS_SET_CERT";